- name: Change password for milad
  hosts: vm
  tasks:
    - name: Set new password for milad
      user:
        name: milad
        password: "{{ 'new_password' | password_hash('sha512', 'secret') }}"
        update_password: always
