- name: Copy SSH public key to remote machine
  hosts: etcd
  become: true
  tasks:
    - name: Add public key to authorized keys
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
